language: objective-c
sudo: false

cache:
  directories:
  - Carthage
  - Inspector/node_modules

before_install:
- |
  if [[ $ACTION == int_test* ]]; then
    rvm install 2.6.2
    rvm use 2.6.2
    bundle install
  fi

script: ./Scripts/build.sh

branches:
  only:
    - master

matrix:
  include:
    # Builds
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=build TARGET=runner SDK=sim
    # Analyze
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=analyze TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=analyze TARGET=runner SDK=sim
    # Unit tests
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=unit_test DEST=iphone TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=unit_test DEST=ipad TARGET=lib SDK=sim
    # Integration tests iPhone
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=int_test_1 DEST=iphone TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=int_test_2 DEST=iphone TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=int_test_3 DEST=iphone TARGET=lib SDK=sim
    # Integration tests iPad
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=int_test_1 DEST=ipad TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=int_test_2 DEST=ipad TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode9.2
      env: IPHONE_MODEL="iPhone SE" IPAD_MODEL="iPad Air 2" IOS_VERSION="11.2" ACTION=int_test_3 DEST=ipad TARGET=lib SDK=sim

    # Builds
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=build TARGET=runner SDK=sim
    # Analyze
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=analyze TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=analyze TARGET=runner SDK=sim
    # Unit tests
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=unit_test DEST=iphone TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=unit_test DEST=ipad TARGET=lib SDK=sim
    # Integration tests iPhone
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=int_test_1 DEST=iphone TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=int_test_2 DEST=iphone TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=int_test_3 DEST=iphone TARGET=lib SDK=sim
    # Integration tests iPad
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=int_test_1 DEST=ipad TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=int_test_2 DEST=ipad TARGET=lib SDK=sim
    - os: osx
      osx_image: xcode10.2
      env: IPHONE_MODEL="iPhone X" IPAD_MODEL="iPad Air 2" IOS_VERSION="12.2" ACTION=int_test_3 DEST=ipad TARGET=lib SDK=sim

    # Builds
    - os: osx
      osx_image: xcode10.2
      env: DEST=tv TV_MODEL="Apple TV" TV_VERSION="12.2" ACTION=build TARGET=tv_runner SDK=tv_sim
    # Analyze
    - os: osx
      osx_image: xcode10.2
      env: DEST=tv TV_MODEL="Apple TV" TV_VERSION="12.2" ACTION=analyze TARGET=tv_runner SDK=tv_sim
