# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  script: ''
  name: ios-e2e-test
  dependsOn: ''
  iosVersion: 13.3
  xcodeVersion: 11.3.1
  deviceName: 'iPhone X'
  skipTvOs: False
  vmImage: 'macOS-11'
  timeoutMin: 60

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: ${{ parameters.timeoutMin }}
    condition: ne(${{ parameters.skipTvOs }}, True)
    variables:
      PLATFORM_VERSION: ${{ parameters.iosVersion }}
      DEVICE_NAME: ${{ parameters.deviceName }}
      MOCHA_FILE: '${{ parameters.name }}-tests.xml'
      LAUNCH_WITH_IDB: ${{ parameters.launchWithIDB }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - checkout: self
    - bash: |
        echo "Mocha output file: $MOCHA_FILE"
        echo "Platform Version: $PLATFORM_VERSION"
        echo "Device Name: $DEVICE_NAME"
      displayName: Print Environment Variables
    - script: ls /Applications/
      displayName: List Installed Applications
    - script: sudo xcode-select -s /Applications/Xcode_${{ parameters.xcodeVersion }}.app/Contents/Developer
      displayName: Xcode Select ${{ parameters.xcodeVersion }}
    - script: xcodebuild -version
      displayName: Log Xcode Version
    - script: xcrun simctl list
      displayName: List Installed Simulators
    - script: xcrun simctl list runtimes
      displayName: List Runtimes
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
    - bash: |
        brew tap facebook/fb
        # use 1.1.7 because xctest doesn't seem to work with 1.1.8 https://github.com/facebook/idb/issues/811
        pushd /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb
        git checkout f660049bdec9965934973052e6331119a4985096
        brew install idb-companion
        popd
        # install idb client
        pip3 install --user fb-idb
      displayName: Install IDB
      condition: eq('${{ parameters.launchWithIDB }}', true)
    - task: NodeTool@0
      inputs:
        versionSpec: 16.x
    - script: |
        npm install -g appium@next
        npm install
        npm run build
      displayName: Install node dependencies
    - script: |
        export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin" || true
        export APPIUM_TEST_SERVER_PORT=4567
        export APPIUM_TEST_SERVER_HOST=127.0.0.1
        export cwd=$(pwd)
        pushd "$cwd"
        cd ~
        appium driver install --source=local "$cwd"
        appium server \
          --port=$APPIUM_TEST_SERVER_PORT \
          --address=$APPIUM_TEST_SERVER_HOST \
          --relaxed-security \
          --keep-alive-timeout 1200 \
          &
        popd
        secondsStarted=$(date +%s)
        while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
          sleep 0.1
          secondsElapsed=$(( $(date +%s) - secondsStarted ))
          if [[ $secondsElapsed -gt 30 ]]; then
            echo "Appium server was unable to start within 30 seconds timeout"
            exit 1
          fi
        done

        ${{ parameters.script }}
      displayName: Run functional tests
