# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
    script: ''
    name: ios-e2e-test
    dependsOn: ''
    iosVersion: 13.0
    xcodeVersion: 11
    deviceName: 'iPhone X'
    skipTvOs: False

jobs:
  - job: ${{ parameters.name }}
    condition: ne(${{ parameters.skipTvOs }}, True)
    variables:
      PLATFORM_VERSION: ${{ parameters.iosVersion }}
      DEVICE_NAME: ${{ parameters.deviceName }}
      MOCHA_FILE: '${{ parameters.name }}-tests.xml'
      LAUNCH_WITH_IDB: ${{ parameters.launchWithIDB }}
      CI: true
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - checkout: self
    - script: |
        echo "Mocha output file: $MOCHA_FILE"
        echo "Platform Version: $PLATFORM_VERSION"
        echo "Device Name: $DEVICE_NAME"
      displayName: Print Environment Variables
    - script: ls /Applications/
      displayName: List Installed Applications
    - script: sudo xcode-select -s /Applications/Xcode_${{ parameters.xcodeVersion }}.app/Contents/Developer
      displayName: Xcode Select ${{ parameters.xcodeVersion }}
    - script: xcodebuild -version
      displayName: Log Xcode Version
    - script: xcrun simctl list
      displayName: List Installed Simulators
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - script: npm install
      displayName: Install node dependencies
    - script: npm run build
      displayName: Build
    - script: ${{ parameters.script }}
      displayName: Run functional tests
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: $(MOCHA_FILE)
    - task: PublishCodeCoverageResults@1
      condition: always()
      inputs:
        codeCoverageTool: cobertura
        summaryFileLocation: coverage/cobertura-coverage.xml
        reporterDirectory: coverage/
