parameters:
  nodeVersion: 16.x
  name: UnitTests
jobs:
  # Run unit tests on different Node versions
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'macOS-12'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.nodeVersion }}
      displayName: Install Node ${{ parameters.nodeVersion }}
    - script: npm install
      displayName: Install node dependencies
    - script: npm run build
      displayName: Build
    - script: npm run lint
      displayName: Lint
    - script: npm run test
      displayName: Unit Test

