parameters:
  nodeVersion: 10.x
  name: UnitTests
jobs:
  # Run unit tests on different Node versions
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.nodeVersion }}
      displayName: Install Node ${{ parameters.nodeVersion }}
    - script: npm install
      displayName: Install node dependencies
    - script: npm test
      displayName: npm test
