parameters:
  matrix: ''
jobs:
  - job: sauce_e2e
    #dependsOn: upload_bundle
    variables:
      MOCHA_FILE: 'SAUCELABS_$(DEVICE_NAME)-$(CLOUD_PLATFORM_VERSION)-tests.xml'
      SAUCE_EMUSIM: true
      CLOUD: true
      CI: true
    strategy:
      maxParallel: 6 # Don't hog all the agents
      matrix: ${{ parameters.matrix }}
    pool:
      vmImage: 'macOS-10.14'
    steps:
    - checkout: self
      submodules: true
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
    - script: |
        npm install
        npm install mocha@5 # Fix until mocha-parallel-tests supports Mocha 6
        npm install mocha-parallel-tests
      displayName: Install node dependencies
    - script: npm run build
      displayName: Build
    - script: npx mocha-parallel-tests --timeout 400000 --max-parallel 0  --reporter mocha-multi-reporters --reporter-options config-file=./ci-jobs/mocha-config.json --require build/test/env/env --recursive 'build/test/functional/basic/' 'build/test/functional/web/' 'build/test/functional/long/'
      displayName: Mocha E2E Tests for $(DEVICE_NAME) $(CLOUD_PLATFORM_VERSION)
      env:
        SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: $(MOCHA_FILE)
