parameters:
  name: ''
  iosVersion: ''
  tvosVersion: ''
  xcodeVersion: ''
  deviceName: 'iphone simulator'
  skipTvOs: False
  tvosName: ''
  tvosDeviceName: ''
  launchWithIDB: false
  vmImage: 'macOS-11'
jobs:
  - template: ./ios-e2e-template.yml
    parameters:
      name: e2e_basic_${{ parameters.name }}
      iosVersion: ${{ parameters.iosVersion }}
      xcodeVersion: ${{ parameters.xcodeVersion }}
      deviceName: ${{ parameters.deviceName }}
      vmImage: ${{ parameters.vmImage }}
      script: |
        npm install --no-save mjpeg-consumer
        npm run e2e-test:basic -- --grep "XCUITestDriver"

  - template: ./ios-e2e-template.yml
    parameters:
      name: e2e_device_${{ parameters.name }}
      iosVersion: ${{ parameters.iosVersion }}
      xcodeVersion: ${{ parameters.xcodeVersion }}
      deviceName: ${{ parameters.deviceName }}
      vmImage: ${{ parameters.vmImage }}
      script: |
        npm run e2e-test:device

  - template: ./ios-e2e-template.yml
    parameters:
      name: e2e_driver_${{ parameters.name }}
      iosVersion: ${{ parameters.iosVersion }}
      xcodeVersion: ${{ parameters.xcodeVersion }}
      deviceName: ${{ parameters.deviceName }}
      vmImage: ${{ parameters.vmImage }}
      launchWithIDB: true
      timeoutMin: 90
      script: npm run e2e-test:driver

  - template: ./ios-e2e-template.yml
    parameters:
      name: e2e_web_${{ parameters.name }}
      iosVersion: ${{ parameters.iosVersion }}
      xcodeVersion: ${{ parameters.xcodeVersion }}
      deviceName: ${{ parameters.deviceName }}
      vmImage: ${{ parameters.vmImage }}
      script: npm run e2e-test:web

  - template: ./ios-e2e-template.yml
    parameters:
      name: e2e_long_${{ parameters.name }}
      iosVersion: ${{ parameters.iosVersion }}
      xcodeVersion: ${{ parameters.xcodeVersion }}
      deviceName: ${{ parameters.deviceName }}
      vmImage: ${{ parameters.vmImage }}
      timeoutMin: 120
      script: |
        npm run e2e-test:long

  # - template: ./ios-e2e-template.yml
  #   parameters:
  #     name: e2e_tvos_${{ parameters.tvosName }}
  #     iosVersion: ${{ parameters.tvosVersion }}
  #     skipTvOs: ${{ parameters.skipTvOs }}
  #     xcodeVersion: ${{ parameters.xcodeVersion }}
  #     deviceName: ${{ parameters.tvosDeviceName }}
  #     vmImage: ${{ parameters.vmImage }}
  #     script: |
  #       npm run e2e-test:parallel

  # FIXME: these tests always fail with a timeout
  # - template: ./ios-e2e-template.yml
  #   parameters:
  #     name: e2e_basic_idb_${{ parameters.name }}
  #     iosVersion: ${{ parameters.iosVersion }}
  #     xcodeVersion: ${{ parameters.xcodeVersion }}
  #     deviceName: ${{ parameters.deviceName }}
  #     launchWithIDB: true
  #     script: |
  #       npm install --no-save mjpeg-consumer
  #       npm run e2e-test:native-web-tap
