# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:

  # TODO: Real device tests go here

  # Run E2E tests on grid of Sauce simulators
  - template: ./templates/sauce-e2e-template.yml
    parameters:
      matrix:
        iPhone_XS_Max_12_0:
          CLOUD_PLATFORM_VERSION: 12.0
          DEVICE_NAME: "iPhone Xs Max Simulator"
        iPhone_7_12_0:
          CLOUD_PLATFORM_VERSION: 11.3
          DEVICE_NAME: "iPhone 7 Simulator"

  # Run the E2E tests on local simulators across different ios and xcode versions
  - template: ./xcuitest-e2e-template.yml
    parameters:
      name: iPhoneXSMax_12_1
      iosVersion: 12.1
      xcodeVersion: 10.1
      deviceName: "iPhone XS Max"
  - template: ./xcuitest-e2e-template.yml
    parameters:
      name: iPhone8_12
      iosVersion: 12.0
      xcodeVersion: 10
      deviceName: "iPhone 8"
  - template: ./xcuitest-e2e-template.yml
    parameters:
      name: iPhone7_11_4
      iosVersion: 11.4
      xcodeVersion: 9.4
      deviceName: "iPhone 7"