# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:

  # Run the E2E tests on 3 (or more) of the most recent Xcode/iOS versions
  - template: ./xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_12_1
      iosVersion: 12.1
      xcodeVersion: 10.1
      deviceName: "iPhone X"
  - template: ./xcuitest-e2e-template.yml
    parameters:
      name: iPhone_8_12
      iosVersion: 12.0
      xcodeVersion: 10
      deviceName: "iPhone 8"
  - template: ./xcuitest-e2e-template.yml
    parameters:
      name: iPhone_7_11_4
      iosVersion: 11.4
      xcodeVersion: 9.4
      deviceName: "iPhone 7"
  
  # Run E2E tests on grid of Sauce simulators
  - job: sauce_e2e
    #dependsOn: upload_bundle
    variables:
      MOCHA_FILE: 'SAUCELABS_$(DEVICE_NAME)-$(CLOUD_PLATFORM_VERSION)-tests.xml'
      SAUCE_EMUSIM: true
      CLOUD: true
      CI: true
    strategy:
      maxParallel: 6 # Don't hog all the agents
      matrix:
        iPhone_XS_Max_12_0:
          CLOUD_PLATFORM_VERSION: 12.0
          DEVICE_NAME: "iPhone Xs Max Simulator"
        iPhone_7_12_0:
          CLOUD_PLATFORM_VERSION: 12.0
          DEVICE_NAME: "iPhone 7 Simulator"
    pool:
      vmImage: 'macOS 10.13'
    steps:
    - checkout: self
      submodules: true
    - script: |
        echo "HAS SAUCE ACCESS KEY"
        echo $SAUCE_ACCESS_KEY
        echo $SAUCE_USERNAME
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
    - script: |
        npm install
        npm install mocha@5 # Fix until mocha-parallel-tests supports Mocha 6
      displayName: Install node dependencies
    - script: npm run build
      displayName: Build
    - script: npx mocha-parallel-tests --timeout 400000 --max-parallel 0  --reporter mocha-junit-reporter --require build/test/env/env --recursive 'build/test/functional/basic/' 'build/test/functional/web/' 'build/test/functional/long/'
      displayName: Mocha E2E Tests for $(DEVICE_NAME) $(CLOUD_PLATFORM_VERSION)
      env:
        SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: $(MOCHA_FILE)
