# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:
  - job: sauce_e2e
    variables:
      CLOUD_PLATFORM_VERSION: 12.0
      DEVICE_NAME: "iPhone Xs Max"
      MOCHA_FILE: 'iphone_xs_max_12.1-tests.xml'
      SAUCE_EMUSIM: true
      CI: true
    #pool:
      #vmImage: 'macOS 10.13'
    steps:
    - checkout: self
      submodules: true
    - task: NodeTool@0
      inputs:
        versionSpec: 11.x
    - script: npm install
      displayName: Install node dependencies
    - script: npm run build
      displayName: Build
    - script: npx mocha-parallel-tests --timeout 400000 --max-parallel 0 --require build/test/env/env --recursive build/test/functional/long/
      displayName: Run functional tests
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFiles: $(MOCHA_FILE)
