# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:

  # Run node tests on past node versions
  - template: ./templates/node-build-template.yml
    parameters:
      nodeVersion: 10.x
      name: Node10_Tests
  - template: ./templates/node-build-template.yml
    parameters:
      nodeVersion: 8.x
      name: Node8_Tests

  # TODO: Real device tests go here

  # Run E2E tests on grid of Sauce simulators
  - template: ./templates/sauce-e2e-template.yml
    parameters:
      matrix:
        # TODO: Add iOS 13 once it is released on Sauce Labs
        iPhone_X_12_2:
          CLOUD_PLATFORM_VERSION: 12.2
          DEVICE_NAME: "iPhone 7 Simulator"
        iPhone_X_Max_12_0:
          CLOUD_PLATFORM_VERSION: 12.0
          DEVICE_NAME: "iPhone 7 Simulator"
        iPhone_7_12_0:
          CLOUD_PLATFORM_VERSION: 11.3
          DEVICE_NAME: "iPhone 7 Simulator"
        iPhone7_11_3:
          CLOUD_PLATFORM_VERSION: 11.3
          DEVICE_NAME: "iPhone 7 Simulator"

  # Run the E2E tests on local simulators across different ios and xcode versions
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneXS_13
      iosVersion: 13.0
      xcodeVersion: 11
      deviceName: "iPhone XS"
      tvosName: AppleTV_13
      tvosDeviceName: "Apple TV"
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneXR_12_2
      iosVersion: 12.2
      xcodeVersion: 10.2
      deviceName: "iPhone XR"
      tvosName: AppleTV_12_2
      tvosDeviceName: "Apple TV"
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneXSMax_12_1
      iosVersion: 12.1
      xcodeVersion: 10.1
      deviceName: "iPhone XS Max"
      tvosName: AppleTV_12_1
      tvosDeviceName: "Apple TV"
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhone7_12
      iosVersion: 12.0
      xcodeVersion: 10
      deviceName: "iPhone 7"
      tvosName: AppleTV_12
      tvosDeviceName: "Apple TV"
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhone7_11_4
      iosVersion: 11.4
      xcodeVersion: 9.4.1
      deviceName: "iPhone 7"
      tvosName: AppleTV_11_4
      tvosDeviceName: "Apple TV"
