# Pull request validation job
jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_14
      iosVersion: 14.0
      xcodeVersion: 12
      deviceName: "iPhone X"
      tvosName: AppleTV_14
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-10.15'
