# Pull request validation job
variables:
- name: SHOW_XCODE_LOG
  value: true
- name: CI
  value: true

stages:
# TODO: Update e2e tests to comply with W3C
- stage: Integration_Tests
  jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_15_2
      iosVersion: 15.2
      xcodeVersion: 14.0
      deviceName: "iPhone Simulator"
      #tvosVersion: 13.4
      #tvosName: AppleTV_13_4
      #tvosDeviceName: "Apple TV"
      skipTvOs: True
      vmImage: 'macOS-12'
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_14_5
      iosVersion: 14.5
      xcodeVersion: 14.0
      deviceName: "iPhone Simulator"
      tvosVersion: 14.5
      tvosName: AppleTV_14_5
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-12'
