# Pull request validation job
jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_13_4
      iosVersion: 13.4
      xcodeVersion: 11.4
      deviceName: "iPhone X"
      tvosName: AppleTV_13_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-10.15'
