# Pull request validation job
variables:
- name: SHOW_XCODE_LOG
  value: true

stages:
- stage: Unit_Tests_And_Linters
  jobs:
  - template: ./templates/node-build-template.yml
    parameters:
      name: UnitTests_CI

- stage: Integration_Tests
  jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_14_4
      iosVersion: 14.4
      xcodeVersion: 12.4
      deviceName: "iPhone Simulator"
      #tvosVersion: 13.4
      #tvosName: AppleTV_13_4
      #tvosDeviceName: "Apple TV"
      skipTvOs: True
      vmImage: 'macOS-10.15'
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_13_4
      iosVersion: 13.4
      xcodeVersion: 11.4
      deviceName: "iPhone Simulator"
      tvosVersion: 13.4
      tvosName: AppleTV_13_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-10.15'
