# Pull request validation job
variables:
- name: SHOW_XCODE_LOG
  value: true

jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_13_7
      iosVersion: 13.7
      xcodeVersion: 11.7
      deviceName: "iPhone X"
      tvosVersion: 13.4
      tvosName: AppleTV_13_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-10.15'
