# Pull request validation job
variables:
- name: SHOW_XCODE_LOG
  value: true

jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_14_2
      iosVersion: 14.0
      xcodeVersion: 12.0.1
      deviceName: "iPhone X"
      tvosVersion: 13.4
      tvosName: AppleTV_13_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-10.15'
