# Pull request validation job
jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_13
      iosVersion: 13.2
      xcodeVersion: 11.3.1
      deviceName: "iPhone X"
      tvosName: AppleTV_13_2
      tvosDeviceName: "Apple TV"
