# Pull request validation job
variables:
- name: SHOW_XCODE_LOG
  value: true
- name: CI
  value: true

stages:
# TODO: Update e2e tests to comply with W3C
- stage: Integration_Tests
  jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhone13_16_2
      iosVersion: 16.2
      xcodeVersion: 14.2
      deviceName: "iPhone 13"
      skipTvOs: True
      vmImage: 'macOS-12'
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhone12_15_5
      iosVersion: 15.5
      xcodeVersion: 13.4
      deviceName: "iPhone 12"
      tvosVersion: 15.4
      tvosName: AppleTV_15_4
      tvosDeviceName: "Apple TV"
      vmImage: 'macOS-12'
