# Pull request validation job
jobs:
  - template: ./templates/xcuitest-e2e-template.yml
    parameters:
      name: iPhoneX_12_2
      iosVersion: 12.2
      xcodeVersion: 10.2
      deviceName: "iPhone X"