# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:
  # TODO: Real device tests go here

  # Run E2E tests on grid of Sauce simulators
  - template: ./templates/sauce-e2e-template.yml
    parameters:
      matrix:
        # TODO: Add iOS 13 once it is released on Sauce Labs
        iPhone_X_12_2:
          CLOUD_PLATFORM_VERSION: 12.2
          DEVICE_NAME: "iPhone 7 Simulator"
        iPhone_X_Max_12_0:
          CLOUD_PLATFORM_VERSION: 12.0
          DEVICE_NAME: "iPhone 7 Simulator"
        iPhone_7_12_0:
          CLOUD_PLATFORM_VERSION: 11.3
          DEVICE_NAME: "iPhone 7 Simulator"
        iPhone7_11_3:
          CLOUD_PLATFORM_VERSION: 11.3
          DEVICE_NAME: "iPhone 7 Simulator"