name: Build Docs

on:
  pull_request:
    paths:
      - 'typedoc.json'
      - 'tsconfig.json'
      - 'scripts/build-docs.js'
      - 'package*.json'
      - 'lib/**/*.ts'
      - 'lib/**/*.js'
      - 'docs/**'
      - '.github/workflows/docs.yml' # this file
      - '!ci-jobs/**'
      - '!**/test/**'
  push:
    paths:
      - 'typedoc.json'
      - 'tsconfig.json'
      - 'scripts/build-docs.js'
      - 'package*.json'
      - 'lib/**/*.ts'
      - 'lib/**/*.js'
      - 'docs/**'
      - '.github/workflows/docs.yml' # this file
      - '!ci-jobs/**'
      - '!**/test/**'

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Install dependencies (Node.js)
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          install-command: npm ci
      - name: Install dependencies (Python)
        run: npm run install-docs-deps
      - name: Build Docs
        run: npm run build:docs
