name: Build Docs

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'typedoc.json'
      - 'tsconfig.json'
      - 'scripts/build-docs.js'
      - 'package*.json'
      - 'lib/**/*.ts'
      - 'lib/**/*.js'
      - 'docs/**'
      - '.github/workflows/docs.yml' # this file
      - '!ci-jobs/**'
      - '!**/test/**'
  push:
    branches: [ master ]
    paths:
      - 'typedoc.json'
      - 'tsconfig.json'
      - 'scripts/build-docs.js'
      - 'package*.json'
      - 'lib/**/*.ts'
      - 'lib/**/*.js'
      - 'docs/**'
      - '.github/workflows/docs.yml' # this file
      - '!ci-jobs/**'
      - '!**/test/**'

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install
        name: Install dependencies
      - name: Install dependencies (Python)
        run: npm run install-docs-deps
      - name: Build Docs
        run: npm run build:docs
