name: Node.js CI
on: [push, pull_request]

jobs:
  # https://thekevinwang.com/2021/09/19/github-actions-dynamic-matrix/
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
    - name: Generate Node.js versions matrix
      id: generate-matrix
      run: |
        current_lts=$(curl -s https://nodejs.org/en/ | grep -E -o 'Download [0-9.]+ LTS' | grep -E -o '([0-9]+)' | head -n 1)
        previous_lts=$(( current_lts - 2 ))
        next_lts=$(( current_lts + 2 ))
        VERSIONS="[$previous_lts, $current_lts, $next_lts]"
        echo ::set-output name=versions::${VERSIONS}

  build:
    runs-on: macos-latest
    needs:
    - prepare_matrix
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.prepare_matrix.outputs.versions) }}
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i -g npm
        npm ci || npm install
      name: Install dev dependencies
    - run: npm run lint
      name: Linter
    - run: npm run test
      name: Unit Tests
