name: Conventional Commits
on:
  pull_request:


jobs:
  lint:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
